# 다음은 template 호출시 10초간 일시정지가 발생하도록 구성한 Workflow이다.

apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: wf-suspend-template
spec:
  entrypoint: steps-template-parallel
  templates:
  - name: steps-template-parallel
    steps:
    - - name: step1
        template: task-template
    - - name: step2
        template: task-template
      - name: step3
        template: task-template
    - - name: delay
        template: delay-template
    - - name: step4
        template: task-template

#template
  - name: task-template
    script:
      image: python:3.8-slim
      command: [python]
      source: |
        print("Task executed.")

  - name: delay-template
    suspend:
      duration: "10s"